version: '3'

services:
  db:
    restart: always
    image: postgres:12-alpine
    container_name: fs-mng-review-db-container
    ports:
      - "29999:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpass
      - PGPASSWORD=localpass
      - POSTGRES_DB=reviewdb
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d/
